#!/bin/zsh
    # dynamische MOTD
    # Aufruf in /etc/profile (letzte Zeile)

echo "
███╗   ███╗███████╗████████╗ █████╗ ██╗      █████╗ ██████╗
████╗ ████║██╔════╝╚══██╔══╝██╔══██╗██║     ██╔══██╗██╔══██╗
██╔████╔██║█████╗     ██║   ███████║██║     ███████║██████╔╝
██║╚██╔╝██║██╔══╝     ██║   ██╔══██║██║     ██╔══██║██╔══██╗
██║ ╚═╝ ██║███████╗   ██║   ██║  ██║███████╗██║  ██║██████╔╝
╚═╝     ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚════╝
"
    # Datum & Uhrzeit
    DATUM=`date +"%A, %e %B %Y"`
    # Hostname
    HOSTNAME=`hostname -f`
    # letzter Login
    LAST1=`last -2 -a | awk 'NR==2{print $3}'`    # Wochentag
    LAST2=`last -2 -a | awk 'NR==2{print $5}'`    # Tag
    LAST3=`last -2 -a | awk 'NR==2{print $4}'`    # Monat
    LAST4=`last -2 -a | awk 'NR==2{print $6}'`    # Uhrzeit
    LAST5=`last -2 -a | awk 'NR==2{print $10}'`    # Remote-Computer
    # Uptime
    UP0=`cut -d. -f1 /proc/uptime`
    UP1=$(($UP0/86400))        # Tage
    UP2=$(($UP0/3600%24))        # Stunden
    UP3=$(($UP0/60%60))        # Minuten
    UP4=$(($UP0%60))        # Sekunden
    # Durchschnittliche Auslasung
    LOAD1=`cat /proc/loadavg | awk '{print $1}'`    # Letzte Minute
    LOAD2=`cat /proc/loadavg | awk '{print $2}'`    # Letzte 5 Minuten
    LOAD3=`cat /proc/loadavg | awk '{print $3}'`    # Letzte 15 Minuten
    # Speicherbelegung
    DISK1=`df -h | grep 'dev/root' | awk '{print $2}'`    # Gesamtspeicher
    DISK2=`df -h | grep 'dev/root' | awk '{print $3}'`    # Belegt
    DISK3=`df -h | grep 'dev/root' | awk '{print $4}'`    # Frei
    # Arbeitsspeicher
    RAM1=`free -h  | grep 'Mem' | awk '{print $2}'`    # Total
    RAM2=`free -h  | grep 'Mem' | awk '{print $3}'`    # Used
    RAM3=`free -h  | grep 'Mem' | awk '{print $4}'`    # Free
    RAM4=`free -h  | grep 'Swap' | awk '{print $3}'`    # Swap used
    # IP-Adressen ermitteln
    if ( ip a | grep -q "eno1" ) ; then IP_LAN=`ip a s eno1 | grep "inet " | cut -d " " -f 6 | cut -d "/" -f 1` ; else IP_LAN="---" ; fi ;
    echo "$DATUM
    Hostname......: $HOSTNAME
    Letzter Login.: $LAST1, $LAST2 $LAST3 $LAST4 von $LAST5
    Uptime........: $UP1 Tage, $UP2:$UP3 Stunden
    Ø Auslastung..: $LOAD1 (1 Min.) | $LOAD2 (5 Min.) | $LOAD3 (15 Min.)
    Speicher......: Gesamt: $DISK1 | Belegt: $DISK2 | Frei: $DISK3
    RAM (MB)......: Gesamt: $RAM1 | Belegt: $RAM2 | Frei: $RAM3 | Swap: $RAM4
    IP-Adresse....: LAN: $IP_LAN"

echo "
This machine is managed by Ansible, your local changes will possibly be futile.
Please discuss beforehand with the people if you want to change something.
"
